src/test/scala/uk/gov/hmrc/test/ui/constants/Errors.scala, src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HaveDefinedContributionPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HaveFlexiblyAccessedPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhenFlexiblyAccessPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhenStopPayingPublicPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/UserJourneyTests.scala
=> add automation scripts for MCSC-243 and MCSC-279

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PayTaxChargeFrom20152016Page.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2012.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2013.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2014.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/UserJourneyTests.scala
=> automate MCSC-244 MCSC-245

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/DateOfBenefitCrystallisationEventPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HadBenefitCrystallisationEventPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/NotAbleToUseThisServiceLtaPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ReportingChangePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhatYouWillNeedLtaPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/UserJourneyTests.scala
=> adding MCSC-247 LTA scripts

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersAnnualAllowanceSetupPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HadBenefitCrystallisationEventPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/LtaProtectionOrEnhancementsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2012.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2013.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2014.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ReasonForResubmissionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ReportingChangePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TaskListPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ToldChangeInLtaPercentagePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhenStopPayingPublicPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/UserJourneyTests.scala, src/test/scala/util/DataCollectorMap.scala
=> add task list,check your answers page related scripts

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/MemberMoreThanOnePensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TaskListPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhatYouWillNeedAaPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AnnualAllowanceUserJourney.scala
=> MCSC-286 automation

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AddAnotherSchemePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersAnnualAllowancePeriodPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersLifetimeAllowancePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/DidYouPayAChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HowExcessWasPaidPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HowMuchLtaChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/MemberMoreThanOnePensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PensionSchemeDetailsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PensionSchemeInputAmountsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2012.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaPreRemedyPage2013.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ProtectionReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ProtectionTypePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhatYouWillNeedAaPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichSchemeDetailsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhoPaidAnnualAllowanceChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AnnualAllowanceUserJourney.scala, src/test/scala/util/DataCollectorMap.scala
=> MCSC-287 scripting

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AdjustedIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ContributedOtherDbDcSchemePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HowMuchPensionPayChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HowMuchYouPayChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDbPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDcPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ThresholdIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TotalIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichContributedDuringRemedyPeriodPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhoPaidAnnualAllowanceChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AnnualAllowanceUserJourney.scala
=> MCSC-288 scripting

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/AdjustedIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PensionSchemeInputAmountsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDbPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDcPensionFlexiblePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TaskListPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ThresholdIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TotalIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhenFlexiblyAccessPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichContributedDuringRemedyPeriodPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AnnualAllowanceUserJourney.scala
=> AA loop scripts

src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersAnnualAllowancePeriodPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersLifetimeAllowancePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HowMuchLtaChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/MemberMoreThanOnePensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ValueNewLtaChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhatYouWillNeedAaPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichContributedDuringRemedyPeriodPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichSchemeDetailsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AnnualAllowanceUserJourney.scala
=> MCSC-372 and MCSC-374

src/test/scala/uk/gov/hmrc/test/ui/pages/AdjustedIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ContributedOtherDbDcSchemePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/MemberMoreThanOnePensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDbPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDcPensionFlexiblePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PiaForDcPensionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ThresholdIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TotalIncomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichContributedDuringRemedyPeriodPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AnnualAllowanceUserJourney.scala
=> update scripts as per MCSC-380

project/Dependencies.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ReportingChangePage.scala
=> MCSC-432 remove adming from the pages

.gitignore, run_browserstacktests.sh, src/test/resources/conf/browserstack.json, src/test/scala/uk/gov/hmrc/test/ui/driver/BrowserDriver.scala, src/test/scala/uk/gov/hmrc/test/ui/driver/SingletonBrowserStackDriver.scala, src/test/scala/uk/gov/hmrc/test/ui/functions/CommonCalculationAAandSchemePaidLTA.scala, src/test/scala/uk/gov/hmrc/test/ui/functions/CommonCalculationAAandUserPaidLTA.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ReportingChangePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/SchemePaidExtraLtaChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/SchemePaidLtaChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAAndLTAJourney2Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAAndLTAJourney3Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAAndLTAJourneyTest.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/LifetimeAllowanceUserJourney.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/tags/BSTests.scala, src/test/scala/util/BrowserStackTestData.scala
=> adding browser stack code and AA and LTA E2E journey

src/test/scala/uk/gov/hmrc/test/ui/pages/SubmissionPage.scala
=> uncommenting submission verification

src/test/scala/uk/gov/hmrc/test/ui/constants/PageInformation.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/Registered.scala
=> address CYA page changes

src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney4Test.scala
=> update test cases

src/test/resources/application.conf, src/test/scala/uk/gov/hmrc/test/ui/conf/TestConfiguration.scala, src/test/scala/uk/gov/hmrc/test/ui/functions/CommonCalculation.scala, src/test/scala/uk/gov/hmrc/test/ui/functions/CommonCalculationAAandMultipleSchemesPaidLTA.scala, src/test/scala/uk/gov/hmrc/test/ui/functions/CommonCalculationAAandSchemeUserPaidLTA.scala, src/test/scala/uk/gov/hmrc/test/ui/functions/CommonCalculationAAandUserPaidLTA.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersCalculationJourneyPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/SignInGovernmentGateway.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/SubmissionPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourney.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney2Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney3Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney4Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney5Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney6Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney7Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourney8Test.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/EndToEndAAJourneyTest.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/LifetimeAllowanceUserJourney.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/UserJourneyValidationTests.scala
Methods for government gateway sign in methods, implemented into existing user journeys
=> Mcsc 670 - government gateway continue without sign in

src/test/scala/uk/gov/hmrc/test/ui/pages/CheckYourAnswersAnnualAllowanceSetupPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/InternationalEnhancementReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/LtaProtectionOrEnhancementsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/MultipleBenefitCrystallisationEventPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/NewInternationalEnhancementReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/NewPensionCreditReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PensionCreditReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/PercentageCausedChangeInChargePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ProtectionChangedNewReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ProtectionChangedNewTypePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ProtectionReferencePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ProtectionTypePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/WhichYearsScottishTaxpayer.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/PRAUserJourneys.scala
pra comments user journeys for calculate service. all passing locally and on jenkins
=> Mcsc 559 new3

src/test/resources/businessCases/request/Scenario_2a_Request.json, src/test/resources/businessCases/response/Scenario_2a_Response.json, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/CalculationLogicVerificationTests.scala
=> add scenarios 2a

src/test/resources/businessCases/request/Scenario_2c_Request.json, src/test/resources/businessCases/request/Scenario_2d_Request.json, src/test/resources/businessCases/request/Scenario_3a_Request.json, src/test/resources/businessCases/response/Scenario_2c_Response.json, src/test/resources/businessCases/response/Scenario_2d_Response.json, src/test/resources/businessCases/response/Scenario_3a_Response.json, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/CalculationLogicVerificationTests.scala
=> Mcsc 790 3

src/test/resources/businessCases/request/Scenario_1c_Request.json, src/test/resources/businessCases/request/Scenario_1d_Request.json, src/test/resources/businessCases/response/Scenario_1c_Response.json, src/test/resources/businessCases/response/Scenario_1d_Response.json, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/CalculationLogicVerificationTests.scala
=> Mcsc 790 2

src/test/scala/uk/gov/hmrc/test/ui/pages/PersonalAllowancePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TaxReliefPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneysFlexIDatesTests.scala
=> add MCSC-841 new pages

src/test/resources/application.conf, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/CalculationLogicVerificationTests.scala
=> add new pages and signin feature to business scenarios

src/test/scala/uk/gov/hmrc/test/ui/pages/AnyLumpSumDeathBenefitsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/HomePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/LumpSumDeathBenefitsValuePage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala
=> add new pages 3.16.6 and 3.16.7

src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala
=> update navigation MCSC878-> 879

src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/CalculationLogicVerificationTests.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TaxReliefAmountPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneysFlexIDatesTests.scala
=> MCSC-929 navigation

src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneysFlexIDatesTests.scala
=> Added coverage on amount validation for marriage allowance

src/test/scala/uk/gov/hmrc/test/ui/pages/DonatedViaGiftAid.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/DonatedViaGiftAidAmount.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneysFlexIDatesTests.scala
GiftAid and Amount pages
All 20scenario of ticket 954
Scenario mapping is as follows:
Income Subjourney 1 = scenario 1, 19
Income Subjourney 2 = scenario 3, 13
Income Subjourney 3 = scenario 2, 14
Income Subjourney 4 = scenario 1, 5
Income Subjourney 5 = scenario 4, 7
Income Subjourney 6 = scenario 1, 11
Income Subjourney 7 = scenario 1, 9
Income Subjourney 8 = scenario 1, 20
Income Subjourney 9 = scenario 1, 20
Income Subjourney 10 = scenario 1, 20
Income Subjourney 11 = scenario 1, 16
Income Subjourney 12 = scenario 1, 15
Income Subjourney 13 = scenario 1, 18
Income Subjourney 14 = scenario 1, 17
Income Subjourney 15 = scenario 1, 6
Income Subjourney 16 = scenario 1, 8
Income Subjourney 17 = scenario 1, 10
Income Subjourney 18 = scenario 1, 12
All tests passing
=> MCSC-954New Gift Aid and amount pages

src/test/scala/uk/gov/hmrc/test/ui/pages/FlexibleAccessDcSchemePage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/IncomeOver190Page.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/AALTATriage1.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneysFlexIDatesTests.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/IncomeSubJourneys1.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/IncomeSubJourneys2.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/IncomeSubJourneys3.scala
=> No jira triage fixes

src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/BusinessScenario2.scala
Please review. Added Business Scenario 2 scripts
=> Add business scenario 2

src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/BusinessScenario3.scala
=> bussiness scenario 3 complete

src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/BusinessScenario1.scala, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/BusinessScenario3.scala, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/BusinessScenario5.scala
=> [MA]Add Business Scenario 5

project/Dependencies.scala, project/build.properties, project/plugins.sbt, src/test/scala/uk/gov/hmrc/test/ui/businessLogicSpecs/BusinessScenario5.scala, src/test/scala/uk/gov/hmrc/test/ui/driver/BrowserDriver.scala
=> Fix Jenkins Issue

src/test/scala/uk/gov/hmrc/test/ui/specs/AALTATriage1.scala
=> 1191 changes commit

src/test/scala/uk/gov/hmrc/test/ui/pages/CalculationResultPage.scala
=> [MCSC-1170][MA]Updated Calculation Results LTA Link

src/test/scala/uk/gov/hmrc/test/ui/pages/PensionSchemeInputAmountsPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneysFlexIDatesTests.scala
=> coverage on split year Revised PIA for 2015-16

src/test/scala/uk/gov/hmrc/test/ui/pages/AuthorityWizardPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ChangePreviousAdjustmentPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/LifetimeAllowanceReviewAnswersPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/ResubmittingAdjustmentPage.scala, src/test/scala/uk/gov/hmrc/test/ui/pages/TaskListPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala
=> Added Coverage for LTA Journey Re login

src/test/scala/uk/gov/hmrc/test/ui/pages/AuthorityWizardPage.scala, src/test/scala/uk/gov/hmrc/test/ui/specs/CalculationUserJourneys.scala
=> Updated the Identifier to Fix the Jenkins Faliure
